[workspace]
resolver = "2"
members = ["crates/*"]
package.edition = "2021"
package.rust-version = "1.65"
package.license = "Apache-2.0"

[profile.release]
debug = 1
lto = true
strip = false
codegen-units = 1
